# (공부) 파이썬 객체 소개_numpy
> 작성완료

- toc:true
- branch: master
- badges: true
- comments: true
- author: kimha02
- categories: [Python]

### `np.array` 

`욕심`: `(1,2,3)+(2,3,4)=(3,5,7)`를 계산하고 싶다. 

(실패)

In [3]:
a=[1,2,3]
b=[2,3,4]
a+b

[1, 2, 3, 2, 3, 4]

(성공)

In [89]:
[a[0]+b[0],a[1]+b[1],a[2]+b[2]]

[3, 5, 7]

(성공2)

In [91]:
a[0]+b[0],a[1]+b[1],a[2]+b[2]

(3, 5, 7)

In [92]:
temp_ = a[0]+b[0],a[1]+b[1],a[2]+b[2]

In [93]:
temp_

(3, 5, 7)

In [94]:
list(temp_)

[3, 5, 7]

-------

- 원소가 많을 경우

(실패)

In [4]:
c=[]
for i in [0,1,2]:
    c[i]=a[i]+b[i]

IndexError: list assignment index out of range

In [5]:
c=[]
c[0]=1

IndexError: list assignment index out of range

In [6]:
c=[]
c=c+[1]

In [104]:
c

[1]

(성공)

In [105]:
c=[]
for i in [0,1,2]:
    c=c+[a[i]+b[i]]

In [106]:
c

[3, 5, 7]

(성공)

In [108]:
a=[1,2,3]
b=[2,3,4]
c=[a[i]+b[i] for i in [0,1,2]]

In [109]:
c

[3, 5, 7]

--------

**- `np array` 사용**

In [88]:
import numpy as np # np는 별칭(맨날 치기 귀찮으니까)

In [80]:
a=np.array((1,2,3))  #우리가 생각하는 벡터 형태, 리스트와 약간 다름!
b=np.array([2,3,4])

In [81]:
a+b

array([3, 5, 7])

`list` - `tuple` - `np.array`사이에는 호환성이 좋음 

In [4]:
a=[1,2,3]

In [5]:
list(np.array(tuple(a)))

[1, 2, 3]


---
넘파이를 사용하면 벡터연산과 행렬연산을 쉽게 할 수 있다. 

예를들어 아래와 같은 문제가 있다고 하자. 

$\begin{cases}
w+2x+3y+4z=1 \\
2w+2x+y=9 \\
x-y=4 \\
3w+x-y+3y=7
\end{cases}$

매트릭스 형태로 위의 식을 표현하면 아래와 같다. 

$\begin{bmatrix}
1 & 2 & 3 & 4 \\ 
2 & 2 & 1 & 0 \\
0 & 1 &-1 & 0 \\
3 & 1 &-1 & 3 
\end{bmatrix}
\begin{bmatrix}
w \\ x \\ y \\z 
\end{bmatrix}=\begin{bmatrix}
1 \\ 9 \\ 4 \\7 
\end{bmatrix}$


양변에 $\begin{bmatrix}
1 & 2 & 3 & 4 \\ 
2 & 2 & 1 & 0 \\
0 & 1 &-1 & 0 \\
3 & 1 &-1 & 3 
\end{bmatrix}$의 역행렬을 취하면 



$\begin{bmatrix}
w \\ x \\ y \\z 
\end{bmatrix}=\begin{bmatrix}
1 & 2 & 3 & 4 \\ 
2 & 2 & 1 & 0 \\
0 & 1 &-1 & 0 \\
3 & 1 &-1 & 3 
\end{bmatrix}^{-1}\begin{bmatrix}
1 \\ 9 \\ 4 \\7 
\end{bmatrix}$

In [87]:
A=[[1,2,3,4],[2,2,1,0],[0,1,-1,0],[3,1,-1,3]]

In [88]:
A

[[1, 2, 3, 4], [2, 2, 1, 0], [0, 1, -1, 0], [3, 1, -1, 3]]

list로 선언된 A를 np.matrix로 변환

In [89]:
Amat=np.matrix(A)

In [90]:
Amat

matrix([[ 1,  2,  3,  4],
        [ 2,  2,  1,  0],
        [ 0,  1, -1,  0],
        [ 3,  1, -1,  3]])

변환된 매트릭스의 역행렬을 구함.

In [91]:
Amat.I

matrix([[-0.15789474,  0.26315789, -0.42105263,  0.21052632],
        [ 0.10526316,  0.15789474,  0.61403509, -0.14035088],
        [ 0.10526316,  0.15789474, -0.38596491, -0.14035088],
        [ 0.15789474, -0.26315789,  0.0877193 ,  0.12280702]])

In [91]:
b=[1,9,4,7]

In [92]:
bvec=np.matrix(b)

In [93]:
bvec

matrix([[1, 9, 4, 7]])

`bvec`은 $1\times 4$ 매트릭스가 된 셈. 

그런데 우리가 원한것은 $4\times 1$ 매트릭스였음. 

In [94]:
bvec=bvec.T
bvec

matrix([[1],
        [9],
        [4],
        [7]])

In [89]:
Amat.I*bvec

matrix([[ 2.],
        [ 3.],
        [-1.],
        [-1.]])

$\begin{bmatrix}
w \\ x \\ y \\z 
\end{bmatrix}=\begin{bmatrix}
1 & 2 & 3 & 4 \\ 
2 & 2 & 1 & 0 \\
0 & 1 &-1 & 0 \\
3 & 1 &-1 & 3 
\end{bmatrix}^{-1}\begin{bmatrix}
1 \\ 9 \\ 4 \\7 
\end{bmatrix}=\begin{bmatrix}
2 \\ 3 \\ -1 \\-1 
\end{bmatrix}$

따라서 $w=2, x=3, y=-1,z=-1$가 된다. 

--------

#### [$\ast$] 배열 vs 행렬 (`np.array` vs `np.matrix`)

아래의 문제를 다시 살펴보자. 

$\begin{bmatrix}
1 & 2 & 3 & 4 \\ 
2 & 2 & 1 & 0 \\
0 & 1 &-1 & 0 \\
3 & 1 &-1 & 3 
\end{bmatrix}
\begin{bmatrix}
w \\ x \\ y \\z 
\end{bmatrix}=\begin{bmatrix}
1 \\ 9 \\ 4 \\7 
\end{bmatrix}$


$(w,x,y,z)$를 풀기위해서는 

In [109]:
A=[[1,2,3,4],[2,2,1,0],[0,1,-1,0],[3,1,-1,3]]
b=[1,9,4,7]
Amat=np.matrix(A)
bvec=np.matrix(b).T
Amat.I * bvec

matrix([[ 2.],
        [ 3.],
        [-1.],
        [-1.]])

그런데 아래처럼 구해도 괜찮다. 

In [95]:
A=[[1,2,3,4],[2,2,1,0],[0,1,-1,0],[3,1,-1,3]]
b=[1,9,4,7]
Aarr=np.array(A)
barr=np.array(b)
np.linalg.inv(Aarr) @barr  # @는 연산자

array([ 2.,  3., -1., -1.])

`np.linalg.inv()`가 통째로 역행렬을 구하는 함수다.

In [97]:
from numpy.linalg import inv
A=[[1,2,3,4],[2,2,1,0],[0,1,-1,0],[3,1,-1,3]]
b=[1,9,4,7]
Aarr=np.array(A)
barr=np.array(b)
inv(Aarr) @ barr  # 함수이름이 너무 길어서 줄여봤음

array([ 2.,  3., -1., -1.])

왜 `np.matrix`를 썼는가? 
- 행렬곱 
- 역행렬계산

`np.matrix`가 진짜 편할까?

**[불만1]** 1차원자료형에 `np.matrix`를 쓰는게 이상하다. 

In [101]:
barr.shape

(4,)

In [102]:
bvec.shape

(4, 1)

이럴꺼면 굳이 1차원 자료형인 `np.array`를 왜 만드는지? 

In [103]:
np.matrix([1,2,3])+np.matrix([4,5,6])

matrix([[5, 7, 9]])

**[불만2]** 3차원 자료가 있다면 어떻게 표현할래? $\to$ 확장성이 부족함

In [16]:
B=[[[1,2],[2,3],[3,4]],[[3,2],[2,2],[4,1]]]

In [17]:
np.array(B)+100

array([[[101, 102],
        [102, 103],
        [103, 104]],

       [[103, 102],
        [102, 102],
        [104, 101]]])

In [18]:
np.matrix(B)+100  

ValueError: matrix must be 2-dimensional

**[불만3]** `np.array`, `np.matrix`가 같이 있으면 혼란이 생긴다.  
            col-vector, row-vector를 굳이 구분하고 싶지 않다.   

내적: $b=\begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}$라는 벡터가 있다고 하자.

벡터의 크기의 제곱: $1^2+2^2+3^2$

벡터의 크기: $\sqrt{1^2+2^2+3^2}$

In [20]:
b=[1,2,3]

In [21]:
np.array(b)@np.array(b)

14

$b=\begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}$, $b^T=[1,2,3]$

$b^T b=[1,2,3]\begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}=1^2+2^2+3^2=14$

$b b^T=\begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}[1,2,3]=\begin{bmatrix}1 & 2 & 3 \\
2 & 4 & 6 \\ 
3 & 6 & 9
\end{bmatrix}$

In [25]:
b1=np.array(b)
b2=np.matrix(b).T
b1

array([1, 2, 3])

In [26]:
b2

matrix([[1],
        [2],
        [3]])

In [27]:
print(b2.T*b2) #... (1)
print(b2*b2.T) #... (2)
#print(b2*b2) ... (3)
#print(b2.T*b2.T) ... (4)

[[14]]
[[1 2 3]
 [2 4 6]
 [3 6 9]]


(1)~(4) 중에 무엇이 맞는 수식인지 따지고 싶지 않다. 

In [28]:
b1@b1 #...(1)
b1@b1.T #...(2)
b1.T@b1 #...(3)
b1.T@b1.T #...(4)

14

In [30]:
A=np.array([[1,0],[0,1]])

In [31]:
A

array([[1, 0],
       [0, 1]])

In [32]:
b=np.matrix([200,300]).T

In [34]:
A*b

matrix([[200],
        [300]])

In [36]:
b*A   # 위치를 바꿀 때 마다 형태를 변형해줘야 하는 불편함이 있음

ValueError: shapes (2,1) and (2,2) not aligned: 1 (dim 1) != 2 (dim 0)

### (3) 인덱싱 (슬라이싱 포함)

In [37]:
A=np.array([[11,12,13,14,15],[21,22,23,24,25],[31,32,33,34,35]])

In [38]:
A

array([[11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35]])

**[예제1]** (3,1)에 접근하여 보자!

(방법1)

In [206]:
A[2]

array([31, 32, 33, 34, 35])

In [39]:
A[2][0]

31

(방법2)

In [41]:
A[2,0] # list와의 차이점 : List에서는 불가능한 문법!

31

**[예제2]** 3행에 접근해보자.

(방법1)

In [208]:
A[2]

array([31, 32, 33, 34, 35])

(방법2)

In [225]:
A[2,0:5]

array([31, 32, 33, 34, 35])

(방법3)

In [42]:
A[2,:]  

array([31, 32, 33, 34, 35])

**[예제3]** 2열에 접근하여 보자. 

(방법1)

In [233]:
A[:,1]

array([12, 22, 32])

**(?)** 아래가 더 읽기 편하지 않나? 

In [43]:
Amat=np.matrix(A)
Amat[:,1]

matrix([[12],
        [22],
        [32]])

(방법2)

In [44]:
A.T[1]

array([12, 22, 32])

**[예제4]** 1행중에서 1,3,5열에 접근해보자. 

(방법1)

In [63]:
A[0,[0,2,4]]

array([11, 13, 15])

(방법2)

In [47]:
A[0][[0,2,4]]  # 가로의 개수를 유지한다고 이해하자

array([11, 13, 15])

(방법3)

In [60]:
b=[0,2,4]

In [61]:
A[0][b]

array([11, 13, 15])

(방법4)

In [62]:
A[0,b]

array([11, 13, 15])

**[예제5]** (1,1),(1,2), (2,1),(2,2) 에 접근하자.

(방법1)

In [270]:
A

array([[11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35]])

In [278]:
A[0:2,0:2]

array([[11, 12],
       [21, 22]])

(방법2)

In [64]:
a=[0,1]
b=[0,1]
A[a,b]  #(0,0), (1,1)이 뽑힌다

array([11, 22])

??? 우리가 원하는게 아니다.

깨달음! 

In [65]:
# A[0,0]
# A[0,1]
# A[1,0]
# A[1,1] 
# * mac : cmd + / 
# * win : ctrl + / 
a=[0,0,1,1]
b=[0,1,0,1]
A[a,b]

array([11, 12, 21, 22])

(방법3)

In [66]:
a=[0,1]
b=[0,1]
A[np.ix_(a,b)]

array([[11, 12],
       [21, 22]])

In [67]:
np.ix_(a,b)

(array([[0],
        [1]]),
 array([[0, 1]]))

**[예제6]**

홀수행, 짝수열을 뽑아보자. 

즉 12,32 14,34 가 뽑혀야함

(방법1)

In [297]:
# A[0,1]
# A[2,1]
# A[0,3]
# A[2,3]

In [295]:
a=[0,2,0,2]
b=[1,1,3,3]
A[a,b]

array([12, 32, 14, 34])

(방법2)

In [299]:
a=[0,2] # 1,3 행 ==> 홀수행
b=[1,3] # 2,4 열 ==> 짝수열 
A[np.ix_(a,b)]

array([[12, 14],
       [32, 34]])

**[예제7]**

2행의 원소중 23보다 작은 원소만? 

(방법1)

In [68]:
#A[1,0] A[1,1]를 뽑고 싶다.
b=[0,1]
A[1,b]

array([21, 22])

하지만 변수가 너무 많을 때는 위와 같이 계산하기당연히 어려움!

(방법2)

아래를 관찰해보자.

In [69]:
c=np.random.normal(size=100)
# np.random.normal(size=100)는 표준정규분포에서 100개의 난수를 생성하는 함수

In [72]:
c>0  #값이 아닌 T/F 결과를 보임

array([False,  True,  True, False, False,  True, False,  True,  True,
       False,  True, False,  True, False,  True,  True, False,  True,
        True, False,  True, False,  True,  True,  True,  True, False,
        True,  True, False, False, False,  True, False,  True, False,
       False, False, False, False, False, False,  True, False, False,
        True,  True, False, False,  True, False, False, False,  True,
        True,  True,  True,  True, False, False,  True, False,  True,
        True, False,  True, False,  True, False,  True,  True,  True,
       False,  True,  True,  True, False, False,  True, False, False,
        True, False,  True,  True, False,  True, False,  True,  True,
        True,  True, False, False,  True, False, False,  True,  True,
        True])

In [74]:
c[c>0]   #boolIndexing->boolidx=c>0

array([0.18334984, 1.77051668, 2.01871979, 0.6618022 , 1.74088515,
       0.67924512, 1.70566946, 0.92208578, 0.77595505, 0.30874189,
       0.20613993, 0.0989423 , 0.89911795, 1.13985843, 1.21816941,
       0.59673282, 0.13421594, 0.55343815, 1.55277558, 0.79995855,
       1.43034953, 0.20047832, 1.4323895 , 0.78760893, 0.17690282,
       0.75236525, 0.65544468, 1.28156261, 0.89955209, 0.87889443,
       0.71509936, 0.12608794, 0.86428365, 0.45614107, 1.26244921,
       0.14842187, 0.43357188, 1.03829107, 1.62379303, 0.91060634,
       1.72900937, 0.52411524, 1.63818633, 0.34336474, 1.27008304,
       0.32455862, 1.13402706, 1.43419411, 1.05120423, 0.02377782,
       0.19521262, 1.73405291, 0.39269412])

이제 응용해보자. 

In [75]:
# c --> A[1]
# c>0 --> A[1]<23 
# c[c>0]는 그러면
A[1][A[1]<23]

array([21, 22])

(방법3)

In [323]:
A[1,:][A[1,:]<23]

array([21, 22])

#### [$\ast$] 인덱싱의 종류 ($\star\star\star$)

1. 기본인덱싱: 인덱스, 슬라이싱을 활용 
   - 예1: `A[1,1]` 
   - 예2: `A[1,0:2]` 
2. 팬시인덱싱(응용인덱싱): 인덱스를 정수배열로 전달, `np.ix_`함수를 활용한 인덱싱, 부울값 인덱싱
    - 예1: `A[0,[0,2,4]]` , 정수배열 인덱싱
    - 예2: `A[np.ix_(a,b)]` , np.ix함수를 활용한 인덱싱
    - 예3: `c[c>0]` , 부울값인덱싱

### (4) `numpy`를 배우는 방법

인터넷+자동완성+contextual help  
도움말을 보고 싶으면 ex)np.reshape **?** 를 해도 볼 수 있다

[$\ast$] 자동완성이 안되면 콘다환경에서 아래를 실행해볼것. 
```
pip install "jedi==0.17.2"
```

In [95]:
a=np.array([1,2,3,2])

In [96]:
np.amax(a)

3

In [100]:
np.reshape(a, [2,2])  # 행렬형태로 변환 가능함

array([[1, 2],
       [3, 2]])

In [343]:
a=np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [345]:
np.reshape(a, (3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])