# (2주차) 3월14일
> constant, concat, stack, tnp
- toc:true
- branch: master
- badges: true
- comments: true
- author: 최규빈
- categories: [Bigdata]

In [1]:
import tensorflow as tf
import numpy as np

- GPU 확인하기

In [2]:
tf.config.experimental.list_physical_devices('GPU')

2022-03-14 19:05:01.108074: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-14 19:05:01.137264: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-14 19:05:01.137808: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero


[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

---

### tf.constant 

#### 예비학습: 중첩리스트 

In [7]:
lst=[1,2]
lst

[1, 2]

In [11]:
lst[0]

1

In [8]:
lst[-1]

2

In [15]:
lst=[[1,2],[3,4]]

In [20]:
lst[1]

[3, 4]

In [21]:
lst[1][0]

3

- 행렬같이 접근할 수 있다. -> 1차원이지만 2차원처럼 생각할 수 있다.

In [ ]:
print(lst[0][0])  #(1,1)

- 열벡터

In [39]:
lst=[1],[2],[3],[4]
lst

([1], [2], [3], [4])

In [40]:
np.array(lst).shape

(4, 1)

- 행벡터

In [36]:
lst=[[1,2,3,4]]
lst

[[1, 2, 3, 4]]

In [38]:
np.array(lst).shape

(1, 4)

#### 선언

- 스칼라

In [45]:
tf.constant(3.14)

2022-03-14 19:25:59.940288: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-03-14 19:25:59.941215: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-14 19:25:59.942112: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-14 19:25:59.942934: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so retur

<tf.Tensor: shape=(), dtype=float32, numpy=3.14>

In [46]:
tf.constant(3.14)+tf.constant(3.14)

<tf.Tensor: shape=(), dtype=float32, numpy=6.28>

- 벡터

In [47]:
tf.constant([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [49]:
_vector=tf.constant([1,2,3])

In [51]:
_vector[-1]

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [52]:
_vector[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

- 매트릭스

In [57]:
_matrix=tf.constant([[1,2],[3,4]])
_matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

- 3차원 벡터(텐서)

In [62]:
_tensor=tf.constant([[[1,2],[3,4]],[[1,2],[3,4]]])
_tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]], dtype=int32)>

#### 타입

In [105]:
type(tf.constant([1,2]))

tensorflow.python.framework.ops.EagerTensor

#### 인덱싱 

In [57]:
_matrix=tf.constant([[1,2],[3,4]])
_matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [65]:
_matrix[0][0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [72]:
_matrix[0] #행뽑기

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [71]:
_matrix[0,:] #행뽑기

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [70]:
_matrix[:,0]  #열뽑기

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3], dtype=int32)>

#### tf.constant는 불편하다. 

`-` 불편한 점
- 모든 원소가 같은 데이터 타입을 가지고 있어야 함.
- 원소 수령이 불가능함.
- 묵시적 변환이 불가능함.
- float + float 계산이 안 됨.

- 원소 수정이 불가능함

In [106]:
a=tf.constant([1,22,33])
a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 1, 22, 33], dtype=int32)>

In [107]:
a[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [93]:
a[0]=[11]  #변경이 안된다

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

---

In [77]:
1+3.14

4.140000000000001

- 타입이 다른 두 숫자의 계산이 가능해보인다.
- 그런데 살펴보면...

In [80]:
tf.constant(1)+tf.constant(3.14)  #여기서는 int+float 안된다.

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2]

In [82]:
tf.constant(1.00)+tf.constant(3.14)  # float으로 바꿔주면 가능...

<tf.Tensor: shape=(), dtype=float32, numpy=4.1400003>

---

In [83]:
tf.constant(1.00)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [85]:
tf.constant(3.14)

<tf.Tensor: shape=(), dtype=float32, numpy=3.14>

In [90]:
tf.constant(1.00, dtype=tf.float64)

<tf.Tensor: shape=(), dtype=float64, numpy=1.0>

In [92]:
tf.constant(1.00, dtype=tf.float64)+tf.constant(3.14)  #float 버전이 다르니까 계산이 안됨.

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a double tensor but is a float tensor [Op:AddV2]

#### tf.constant $\to$ 넘파이 

In [94]:
np.array(1)+np.array(3.14)

4.140000000000001

In [97]:
tf.constant(np.array([[1,2],[3,4]]))

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[1, 2],
       [3, 4]])>

- 텐서를 넘파이로 바꾸는 법

In [98]:
np.array(tf.constant(1))

array(1, dtype=int32)

In [100]:
a=tf.constant(3.14)
type(a)

tensorflow.python.framework.ops.EagerTensor

In [104]:
a.numpy()

3.14

#### 연산

`-` 더하기

In [110]:
tf.constant([1,2])+tf.constant([3,4])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>

In [111]:
a=tf.constant([1,2])
b=tf.constant([3,4])
a+b

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>

In [112]:
tf.add(a,b)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>

In [114]:
tf.add([1,2],[5,6])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([6, 8], dtype=int32)>

`-` 곱하기

In [133]:
a=tf.constant([[1,2],[3,4]])
b=tf.constant([[5,6],[7,8]])
a*b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]], dtype=int32)>

In [134]:
tf.multiply(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]], dtype=int32)>

`-` 일반적인 매트릭스 곱

In [131]:
a=tf.constant([[1,0],[0,1]]) #(2,2)
b=tf.constant([[5],[7]]) #(2,1)
a@b 

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[5],
       [7]], dtype=int32)>

In [132]:
tf.matmul(a,b)

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[5],
       [7]], dtype=int32)>

`-` 역행렬

In [123]:
a=tf.constant([[1,0],[0,2]])
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 2]], dtype=int32)>

In [125]:
tf.linalg.inv(a)  #1/2를 만들려면 int는 안되고 float으로 해야 한다는 오류...

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: double, float, half, complex64, complex128
	; NodeDef: {{node MatrixInverse}}; Op<name=MatrixInverse; signature=input:T -> output:T; attr=adjoint:bool,default=false; attr=T:type,allowed=[DT_DOUBLE, DT_FLOAT, DT_HALF, DT_COMPLEX64, DT_COMPLEX128]> [Op:MatrixInverse]

In [127]:
a=tf.constant([[1.0,0.0],[0.0,2.0]])
tf.linalg.inv(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1. , 0. ],
       [0. , 0.5]], dtype=float32)>

`-` `tf.linalg` + `tab` 에서 몇 개 응용

In [136]:
a=tf.constant([[1.0,2.0],[3.0,4.0]])
print(a)
tf.linalg.det(a)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


<tf.Tensor: shape=(), dtype=float32, numpy=-2.0>

In [138]:
tf.linalg.trace(a)  #대각 원소의 합

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

#### 형태변환

`-` 기본 : `tf.reshape()`를 이용

In [142]:
a=tf.constant([1,2,3,4])  #그냥 길이가 4인 벡터
a

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [143]:
tf.reshape(a, (4,1))  #4X1 매트릭스로

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4]], dtype=int32)>

In [146]:
tf.reshape(a, (2,2))  

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [147]:
tf.reshape(a, (2,2,1))  #3차원도 가능하다

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

`-` 다차원

In [148]:
a=tf.constant([1,2,3,4,5,6,7,8,9,10,11,12])
a

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32)>

In [149]:
tf.reshape(a,(2,2,3))

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [150]:
tf.reshape(a,(4,3))

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

`-` `tf.resh` : 알아서 짝을 찾아주면 안되나? 안되면 그냥 에러메세지를 띄워줘

In [153]:
a=tf.constant([1,2,3,4,5,6,7,8,9,10,11,12])
a

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32)>

In [154]:
tf.reshape(a,(4,-1))  #-1은 물음표 역할

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [156]:
tf.reshape(a,(2,2,-1))

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [159]:
b=tf.reshape(a,(2,2,-1))
b

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [160]:
tf.reshape(b,-1)  #그냥 벡터로 만들어줘

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32)>

#### 선언고급 

`-` 다른 자료형(리스트, 넘파이 등)로 만들고 바꾸는 것도 좋음!

In [162]:
np.diag([1,2,3,4])  #대각행렬

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [164]:
tf.constant(np.diag([1,2,3,4]))  #넘파이->텐서

<tf.Tensor: shape=(4, 4), dtype=int64, numpy=
array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])>

`-` `tf.ones`, `tf.zeros`

In [165]:
tf.zeros([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [170]:
tf.reshape(tf.constant([0]*9),(3,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)>

`-` `range(10)`

In [178]:
a=range(0,10)  #그냥 range(0,10)은 아무 정보가 없다
list(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [181]:
a=range(0,12)  
tf.constant(a)

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)>

In [184]:
list(range(5))   #0은 생략할 수 있음, 마지막 숫자는 빠진다.

[0, 1, 2, 3, 4]

In [186]:
list(range(1,5))   #1에서 시작하지만 여전히 5는 안들어감

[1, 2, 3, 4]

In [187]:
list(range(1,20,3))   #3칸씩 빼고

[1, 4, 7, 10, 13, 16, 19]

In [189]:
tf.constant(range(1,20,3))  #3칸씩 빼고

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([ 1,  4,  7, 10, 13, 16, 19], dtype=int32)>

`-` `tf.linspace`

In [191]:
tf.linspace(0,1,10)  #0~1까지 10개 뽑기, 여기선 1이 포함된다.

<tf.Tensor: shape=(10,), dtype=float64, numpy=
array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])>

#### tf.concat 

In [194]:
a=tf.constant([[1],[2]])
b=tf.constant([[3],[4]])
a,b

(<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
 array([[1],
        [2]], dtype=int32)>,
 <tf.Tensor: shape=(2, 1), dtype=int32, numpy=
 array([[3],
        [4]], dtype=int32)>)

`-` (2,1) concat (2,1) => (4,1)
- 첫번째 축이 바뀌었음. => axis=0

In [199]:
tf.concat([a,b],axis=0)  #axis입력 필수

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4]], dtype=int32)>

`-` (2,1) concat (2,1) => (2,2)
- 두번째 축이 바뀌었음. => axis=1

In [200]:
tf.concat([a,b],axis=1)  #axis입력 필수

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]], dtype=int32)>

`-` (1,2) concat (1,2) => (2,2)
- 첫번째가 바뀌니까 axis=0

In [208]:
a=tf.constant([[1,2]])
b=tf.constant([[3,4]])

In [209]:
tf.concat([a,b],axis=0)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

`-` (1,2) concat (1,2) => (1,4)
- 첫번째가 바뀌니까 axis=1

In [208]:
a=tf.constant([[1,2]])
b=tf.constant([[3,4]])

In [210]:
tf.concat([a,b],axis=1)

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[1, 2, 3, 4]], dtype=int32)>

`-` 차원을 늘려보자!  
`-` (2,3,4,5) concat (2,3,4,5) => (4,3,4,5)  
- 첫번째 -> axis=0

In [215]:
a=tf.reshape(tf.constant(range(120)), (2,3,4,5))
b=-a

In [218]:
tf.concat([a,b],axis=0).shape

TensorShape([4, 3, 4, 5])

`-` (2,3,4,5) concat (2,3,4,5) => (2,6,4,5)  
- 두번째 -> axis=1

In [219]:
a=tf.reshape(tf.constant(range(120)), (2,3,4,5))
b=-a

In [220]:
tf.concat([a,b],axis=1).shape

TensorShape([2, 6, 4, 5])

`-` (2,3,4,5) concat (2,3,4,5) => (2,3,8,5)  
- 세번째 -> axis=2

In [221]:
a=tf.reshape(tf.constant(range(120)), (2,3,4,5))
b=-a

In [222]:
tf.concat([a,b],axis=2).shape

TensorShape([2, 3, 8, 5])

`-` (2,3,4,5) concat (2,3,4,5) => (2,3,4,10)  
- 네번째 -> axis=3, -1

In [223]:
a=tf.reshape(tf.constant(range(120)), (2,3,4,5))
b=-a

In [225]:
tf.concat([a,b], axis=-1).shape

TensorShape([2, 3, 4, 10])

In [226]:
tf.concat([a,b], axis=3).shape

TensorShape([2, 3, 4, 10])

`-` 차원을 줄여보자!  
`-` (4,) concat (4,) => (8,)
- 첫번째 축이 변하는게 맞나?
- `axis=0` 이 잘 실행됨. 

In [236]:
a=tf.constant([1,2,3,4])
b=-a
a,b

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([-1, -2, -3, -4], dtype=int32)>)

In [237]:
tf.concat([a,b],axis=0).shape

TensorShape([8])

`-` 1이 생략된건가?  
`-` (4,) concat (4,) => (4,2)
- 두번째 축 => axis=2  ==> **안된다.** 왜냐하면 1이 생략된 것이 아니라 그냥 1차원이기 때문에

In [234]:
a=tf.constant([1,2,3,4])
b=-a
a,b

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([-1, -2, -3, -4], dtype=int32)>)

In [239]:
tf.concat([a,b], axis=1).shape

InvalidArgumentError: ConcatOp : Expected concatenating dimensions in the range [-1, 1), but got 1 [Op:ConcatV2] name: concat

#### tf.stack 

`-` 위에서 못한 거 stack으로 가능!

In [234]:
a=tf.constant([1,2,3,4])
b=-a
a,b

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([-1, -2, -3, -4], dtype=int32)>)

In [243]:
tf.stack([a,b])  #근데 2X4 매트릭스다. 왜냐면 디폴트가 axis=0여서

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [-1, -2, -3, -4]], dtype=int32)>

In [244]:
tf.stack([a,b], axis=1) 

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 1, -1],
       [ 2, -2],
       [ 3, -3],
       [ 4, -4]], dtype=int32)>

- concat은 매트릭스를 합치면 매트릭스가 나온다. 벡터를 합쳐서 매트릭스 안 됨.
- 하지만 stack은 벡터 합쳐서 매트릭스가 가능함.

### tnp

> tnp = tensorflow+numpy

`-` 텐서 만들기가 너무 힘듦.

In [251]:
np.diag([1,2,3]).reshape(-1)

array([1, 0, 0, 0, 2, 0, 0, 0, 3])

#### tnp 사용방법 (불만해결방법)

In [245]:
import tensorflow.experimental.numpy as tnp

In [247]:
tnp.experimental_enable_numpy_behavior()  #동작을 위한 모드를 키는? 

In [249]:
type(tnp.array([1,2,3]))

tensorflow.python.framework.ops.EagerTensor

`-` `int`와 `float`을 더할 수 있음.

In [252]:
tnp.array([1,2,3])+tnp.array([1.0,2.0,3.0])

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 4., 6.])>

In [255]:
tnp.array(1)+tnp.array([1.0,2.0,3.0])  #브로드캐스팅 다름(차원이 달라도 계산 가능)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 3., 4.])>

In [257]:
tf.constant([1,2,3])+tf.constant([1.0,2.0,3.0])  #원래 안되던 것도 모드를 키면 넘파이처럼 동작함

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 4., 6.])>

In [258]:
tnp.diag([1,2,3])

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])>

In [261]:
a=tnp.diag([1,2,3])
type(a)  #텐서 그대로 나옴

tensorflow.python.framework.ops.EagerTensor

In [263]:
a.min()   #최소값 찾기

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [265]:
a.reshape(-1)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 0, 0, 0, 2, 0, 0, 0, 3])>

In [266]:
a=tf.constant([1,2,3])
a.reshape(3,1)

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3]], dtype=int32)>

#### **선언, 선언고급**

In [268]:
np.random.randn(5)  #정규분포에서 뽑기

array([ 0.449788  ,  1.9891379 , -0.47806401,  1.23461833, -0.64734895])

In [269]:
tnp.random.randn(5)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([-0.20001553,  0.93705984, -0.64863757,  1.26619036, -0.23964021])>

#### 타입

In [270]:
type(tnp.random.randn(5))

tensorflow.python.framework.ops.EagerTensor

#### tf.contant로 만들어도 마치 넘파이인듯 쓰는 기능들

**[장점들]**

`-` 묵시적 형변환이 가능 -> `int` + `float` 계산 가능!

`-` `method`의 종류가 아주 많아졌다는 것! -> `.`을 찍어 실행하는 것들


In [273]:
a=tnp.array([[1,2,3,4]])
a.T

<tf.Tensor: shape=(4, 1), dtype=int64, numpy=
array([[1],
       [2],
       [3],
       [4]])>

#### 그렇지만 np.array는 아님 

In [274]:
a=tf.constant([1,2,3])

In [275]:
a.reshape(3,1)

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3]], dtype=int32)>

- 여기까지는 잘 실행된다.
- 하지만

In [276]:
a[0]=11

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

- 값 바꾸기는 여전히 안 됨.