# (3주차) 3월21일 
- toc:true
- branch: master
- badges: true
- comments: true
- author: 최규빈

---

### imports 

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.config.experimental.list_physical_devices('GPU')

2022-03-21 18:55:30.391830: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-21 18:55:30.412866: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-21 18:55:30.413250: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero


[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

- 데이터과학 수업 참고하기

---

### 지난강의 보충 

`-` max, min, sum, mean 

In [5]:
a=tf.constant([1,2,3,4])
a

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [7]:
#max
max(a)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [9]:
#mean은 안 된다.
mean(a)

NameError: name 'mean' is not defined

In [11]:
tf.reduce_mean(a)
#잘못구해졌다.

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [12]:
a=tf.constant([1.0,2.0,3.0,4.0])
a

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>

In [15]:
tf.reduce_mean(a)
#잘 구해진 모습, 하지만 그렇게 잘 쓰진 않음. tnp가 있으니까

<tf.Tensor: shape=(), dtype=float32, numpy=2.5>

#### concat, stack 

`-` 예제: (2,3,4,5) stack (2,3,4,5) -> (?,?,?,?,?)

In [18]:
a=tf.reshape(tf.constant(range(2*3*4*5)),(2,3,4,5))
b=-a

**case 1**  
(1,2,3,4,5) stack (1,2,3,4,5) = (2,2,3,4,5) #axis=0

In [21]:
tf.stack([a,b],axis=0).shape

TensorShape([2, 2, 3, 4, 5])

**case 2**  
(2,1,3,4,5) stack (2,1,3,4,5) = (2,2,3,4,5)  #axis=1

In [22]:
tf.stack([a,b],axis=1).shape

TensorShape([2, 2, 3, 4, 5])

**case 3**  
(2,3,1,4,5) stack (2,3,1,4,5) = (2,3,2,4,5)  #axis=2

In [23]:
tf.stack([a,b],axis=2).shape

TensorShape([2, 3, 2, 4, 5])

**case 4**  
(2,3,4,1,5) stack (2,3,4,1,5) = (2,2,4,2,5)  #axis=3

In [24]:
tf.stack([a,b],axis=3).shape

TensorShape([2, 3, 4, 2, 5])

In [27]:
tf.stack([a,b],axis=-2).shape

TensorShape([2, 3, 4, 2, 5])

**case 5**  
(2,3,4,5,1) stack (2,3,4,5,1) = (2,3,4,5,2)  #axis=4

In [25]:
tf.stack([a,b],axis=4).shape

TensorShape([2, 3, 4, 5, 2])

In [26]:
tf.stack([a,b],axis=-1).shape

TensorShape([2, 3, 4, 5, 2])

`-` 예제: (2,3,4), (2,3,4), (2,3,4)

In [28]:
a=tf.reshape(tf.constant(range(2*3*4)),(2,3,4))
b=-a
c=2*a

(예시1) (2,3,4), (2,3,4), (2,3,4) $\to$ (6,3,4)

In [30]:
tf.concat([a,b,c], axis=0).shape

TensorShape([6, 3, 4])

(예시2) (2,3,4), (2,3,4), (2,3,4) $\to$ (2,9,4)

In [31]:
tf.concat([a,b,c], axis=1).shape

TensorShape([2, 9, 4])

(예시3) (2,3,4), (2,3,4), (2,3,4) $\to$ (2,3,12)

In [32]:
tf.concat([a,b,c], axis=2).shape

TensorShape([2, 3, 12])

(예시4) (2,3,4), (2,3,4), (2,3,4) $\to$ (3,2,3,4)


In [33]:
tf.stack([a,b,c], axis=0).shape

TensorShape([3, 2, 3, 4])

(예시5) (2,3,4), (2,3,4), (2,3,4) $\to$ (2,3,3,4)

In [34]:
tf.stack([a,b,c], axis=1).shape

TensorShape([2, 3, 3, 4])

(예시6) (2,3,4), (2,3,4), (2,3,4) $\to$ (2,3,3,4) 

In [35]:
tf.stack([a,b,c], axis=2).shape

TensorShape([2, 3, 3, 4])

In [36]:
tf.stack([a,b,c], axis=-2).shape

TensorShape([2, 3, 3, 4])

(예시7) (2,3,4), (2,3,4), (2,3,4) $\to$ (2,3,4,3) 

In [37]:
tf.stack([a,b,c], axis=3).shape

TensorShape([2, 3, 4, 3])

In [38]:
tf.stack([a,b,c], axis=-1).shape

TensorShape([2, 3, 4, 3])

- concat과 stack의 차이점을 잘 알고 잇짜!

`-` 예제: (2,3,4) (4,3,4) $\to$ (6,3,4) 

In [44]:
a=tf.reshape(tf.constant(range(2*3*4)),(2,3,4))
b=tf.reshape(-tf.constant(range(4*3*4)),(4,3,4))

In [48]:
tf.concat([a,b],axis=0).shape

TensorShape([6, 3, 4])

In [50]:
tf.concat([a,b],axis=1).shape
#dimension이 달라서 안된다.

InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [2,3,4] vs. shape[1] = [4,3,4] [Op:ConcatV2] name: concat

In [51]:
tf.concat([a,b],axis=-1).shape
#dimension이 달라서 안된다.

InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [2,3,4] vs. shape[1] = [4,3,4] [Op:ConcatV2] name: concat

`-` (2,2) @ (2,) 의 연산? 

**numpy**

In [54]:
#numpy
np.array([[1,0],[0,1]])@ np.array([77,-88])

array([ 77, -88])

In [55]:
#numpy
np.array([77,-88]) @ np.array([[1,0],[0,1]])

array([ 77, -88])

- 알아서 열/행벡터인지 인식하여 해준다?

In [56]:
#열벡터로 지정해서 한다면?
np.array([[1,0],[0,1]])@ np.array([77,-88]).reshape(2,1)

array([[ 77],
       [-88]])

In [58]:
#열벡터로 지정해서 한다면?_이 때는 사이즈를 명시해주니까 계산 에러남.
np.array([77,-88]).reshape(2,1) @ np.array([[1,0],[0,1]])

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

In [59]:
#행벡터로 지정해서 한다면?
np.array([77,-88]).reshape(1,2) @ np.array([[1,0],[0,1]])

array([[ 77, -88]])

- 넘파이에서 길이가 2인 벡터는 매트릭스 앞뒤로 곱해주면 알아서 해석이 되어 결과가 나옴. 하지만 결과는 1차원 유지.
- 명시적으로 shape을 바꿔주면 결과도 shape에 맞춰서 나옴. 에러메세지도 나온다.

**tensorflow**

- 하지만 tf.constant는 알아서 계산은 안됨.

In [68]:
I=tf.constant([[1.0,0.0],[0.0,1.0]])
x=tf.constant([77.0,-88.0])

In [69]:
I@x

InvalidArgumentError: In[0] and In[1] has different ndims: [2,2] vs. [2] [Op:MatMul]

In [70]:
x@I

InvalidArgumentError: In[0] and In[1] has different ndims: [2] vs. [2,2] [Op:MatMul]

In [71]:
I @ tf.reshape(x,(2,1))

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[ 77.],
       [-88.]], dtype=float32)>

In [74]:
tf.reshape(x,(1,2)) @ I 

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[ 77., -88.]], dtype=float32)>

In [79]:
tf.reshape(x,[1,2]) @ I 

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[ 77., -88.]], dtype=float32)>

In [76]:
tf.reshape(x,(2,1))

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[ 77.],
       [-88.]], dtype=float32)>

---

### tf.Variable

#### 선언 

`-` tf.Variable()로 선언

In [80]:
tf.Variable([1,2,3,4])

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [81]:
tf.Variable([1.0,2.0,3.0,4.0])

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>

`-` tf.constant() 선언후 변환

In [85]:
_a=tf.Variable([1,2,3,4])
type(_a)   #약간 우리가 이전에 쓰던 모양과 다르다.

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [87]:
tf.Variable(tf.constant([1,2,3,4]))

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

`-` np 등으로 선언후 변환 

In [89]:
tf.Variable(np.array([1,2,3,4]))

<tf.Variable 'Variable:0' shape=(4,) dtype=int64, numpy=array([1, 2, 3, 4])>

❓ : `tf.Variable` 이 가진 장점

#### 타입

In [90]:
type(tf.Variable([1,2,3,4]))

tensorflow.python.ops.resource_variable_ops.ResourceVariable

#### 인덱싱 

In [91]:
a=tf.Variable([1,2,3,4])
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [92]:
a[:2]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [97]:
type(a[:2]) #tf.constant와 같아졌다!

tensorflow.python.framework.ops.EagerTensor

#### 연산가능 

In [94]:
a=tf.Variable([1,2,3,4])
b=tf.Variable([-1,-2,-3,-4])

In [95]:
a+b

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 0, 0, 0], dtype=int32)>

In [98]:
type(a+b)

tensorflow.python.framework.ops.EagerTensor

**- 연산하는 순간 `type`이 바뀐다!**

#### $\to$ tf.Variable도 쓰기 불편함 

In [99]:
#다른 불편한 예제
tf.Variable([1,2])+tf.Variable([3.14,3.14])

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2]

#### tnp의 은총도 일부만 가능 

In [100]:
import tensorflow.experimental.numpy as tnp
tnp.experimental_enable_numpy_behavior()

`-` 알아서 형 변환 

In [101]:
tf.Variable([1,2])+tf.Variable([3.14,3.14])

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([4.1400001, 5.1400001])>

`-` .reshape 메소드 

In [105]:
tf.constant([1,2,3,4]).reshape(2,2)  #constant는 tnp를 키면 이렇게 된다

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [104]:
tf.Variable([1,2,3,4]).reshape(2,2) #이건 또 안 된다

AttributeError: 'ResourceVariable' object has no attribute 'reshape'

#### 대부분의 동작은 tf.constant랑 큰 차이를 모르겠음 

`-` tf.concat 

In [107]:
a=tf.Variable([[1,2],[3,4]])
#b=-a를 하면 Variable이 깨진다
b=tf.Variable([[-1,-2],[-3,-4]])
tf.concat([a,b],axis=0)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 1,  2],
       [ 3,  4],
       [-1, -2],
       [-3, -4]], dtype=int32)>

`-` tf.stack

In [108]:
a=tf.Variable([[1,2],[3,4]])
b=tf.Variable([[-1,-2],[-3,-4]])
tf.stack([a,b],axis=0)

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4]],

       [[-1, -2],
        [-3, -4]]], dtype=int32)>

- tnp의 장점이 Variable에서 100% 적용이 안되고,
- 연산만 하면 자료형이 바뀐다...  
$\to$ Variable 단점

#### 변수값변경가능(?) $\to$  장점?

- 재할당 이해하기 : 1에 a라는 이름을 붙엿던 것을 456에 a라는 이름을 붙이는 것. 따라서 주소가 다름.  
- $\to$ 이런 것을 `불변형`이라고 함. 불변형을 쓰면 메모리 소모가 많음. 자원이 풍부해야 한다... (Ex.R)
- 만약 주소가 같다면 `편집`이라고 함. `편집`은 a를 1에서 456으로 바꾸는 것
- $\to$ 이런 것을 `가변형`이라고 함. 

- parameter는 GPU, x는 CPU에 올려야 계산이 된다. 메모리를 아끼기 위함임(?)

In [111]:
a=1
id(a)

139639058841840

In [ ]:
a=456
id(a)

- Variable을 보면..

In [115]:
a=tf.Variable([1,2,3,4])
id(a)

139630864641872

In [116]:
a.assign_add([-1,-2,-3,-4])
id(a)

139630864641872

- 주소 값이 같다

---

#### 요약 

`-` tf.Variable()로 만들어야 하는 뚜렷한 차이는 모르겠음. 

`-` 애써 tf.Variable()로 만들어도 간단한 연산을 하면 그 결과는 tf.constant()로 만든 오브젝트와 동일해짐. (결국 GPU 메모리를 아끼기 위함이다..., `to.(cpu)`개념인가?)

---

### 미분 

- 선형계산이기 때문에 GPU로 계산하면 정말 빠르다! 😊

#### 모티브

`-` 예제: 컴퓨터를 이용하여 $x=2$에서 $y=3x^2$의 접선의 기울기를 구해보자. 

(손풀이)
> $\frac{dy}{dx}$=6x
이므로 $x=2$를 대입하면 $12$가 정답!

(컴퓨터를 이용한 풀이)

**단계 1**

In [118]:
x1=2
y1=3*x1**2

In [119]:
x2=2+0.000000001
y2=3*x2**2

In [120]:
(y2-y1)/(x2-x1)

12.0

**단계 2** : 함수로 만들자.

In [121]:
def f(x) : 
    return 3*x**2

In [124]:
f(3)

27

In [125]:
def d(f,x) :
    return (f(x+0.000000001)-f(x))/0.000000001

In [126]:
d(f,2)

12.000000992884452

**단계 3** : 항상 선언하기는 좀 이상하다.

In [127]:
d(lambda x: 3*x**2, 2)

12.000000992884452

In [128]:
d(lambda x: x**2, 0)

1e-09

**단계 4** : 더 확장성 있게...

$$f(x,y)=x^2+3y$$  
를 x로만 편미분하고 싶을 때,

In [132]:
def f(x,y) :
    return (x**2 +3*y)

In [133]:
d(f,(2,3))

TypeError: can only concatenate tuple (not "float") to tuple

#### tf.GradientTape() 사용방법 

`-` 예제1: $x=2$에서 $y=3x^2$의 도함수값을 구하라. 

In [154]:
tf.GradientTape()
#Gradient=기울기, Tape=기록할 수 있는 공간

`0x7efe58153ac0` 이거를 잘 기억하기! 정보가 여기에 위치하고 있다.

In [162]:
#dir(mytape)  #숨겨진 목록도 함께 확인하자, enter, exit 주목하기

In [167]:
x=tf.Variable(2.0)  #미분하고 싶은 애를 Variable로 잡고, 기울기를 구하고 싶은 지점을 숫자로 써라->외우기
a=tf.constant(3.0)  #계수인 3도 저장해놓자

mytape=tf.GradientTape()
mytape.__enter__()  #기록 시작
y=a*x**2 
mytape.__exit__(None,None,None)  #기록 끝

mytape.gradient(y,x)  #y를 x로 미분하라.

<tf.Tensor: shape=(), dtype=float32, numpy=12.0>

`-` 예제2: 조금 다른예제 

In [168]:
x=tf.Variable(2.0)  #미분하고 싶은 애를 Variable로 잡고, 기울기를 구하고 싶은 지점을 숫자로 써라->외우기
#a=tf.constant(3.0)  #계수인 3도 저장해놓자

mytape=tf.GradientTape()
mytape.__enter__()  #기록 시작
a=x/2*3  ##a=(3/2)x
y=a*x**2  ## y=ax^2=(3/2)x^3
mytape.__exit__(None,None,None)  #기록 끝

mytape.gradient(y,x)  #y를 x로 미분하라.

<tf.Tensor: shape=(), dtype=float32, numpy=18.0>

$$a=\frac{3}{2}x$$
$$y=ax^2=\frac{3}{2}x^3$$
$$\frac{dy}{dx} = \frac{3}{2} 3x^2$$

In [169]:
3/2*3*4

18.0

`-` 테이프의 개념 ($\star$)

(상황) 

우리가 어려운 미분계산을 컴퓨터에게 부탁하는 상황임. (예를들면 $y=3x^2$) 컴퓨터에게 부탁을 하기 위해서는 연습장(=테이프)에 $y=3x^2$이라는 수식을 써서 보여줘야하는데 이때 컴퓨터에게 target이 무엇인지 그리고 무엇으로 미분하고 싶은 것인지를 명시해야함. 

✏️  
(1) `mytape = tf.GradientTape()`: tf.GradientTape()는 컴퓨터에게 보여줄 연습장 만드는 명령어, 만들어진 연습장에 mytape라고 이름을 붙인다.

(2) `mytape.__enter__()`: 만들어진 공책을 연다.(= 기록할 수 있는 상태로 만든다)

(3) `a=x/2*3; y=a*x**2`: 컴퓨터에게 전달한 수식을 쓴다.

(4) `mytape.__exit__(None,None,None)`: 공책을 닫는다.

(5) `mytape.gradient(y,x)`: $y$를 $x$로 미분하라는 메모를 남기고 컴퓨터에게 전달한다.

`-` 예제3: 연습장을 언제 열고 닫을지 결정하는건 중요하다. 

In [171]:
x=tf.Variable(2.0)  #미분하고 싶은 애를 Variable로 잡고, 기울기를 구하고 싶은 지점을 숫자로 써라->외우기
a=x/2*3  ##a=(3/2)x, 계산결과만 보게 됨

mytape=tf.GradientTape()
mytape.__enter__()  #기록 시작
y=a*x**2  ## y=ax^2
mytape.__exit__(None,None,None)  #기록 끝

mytape.gradient(y,x)  #y를 x로 미분하라.

<tf.Tensor: shape=(), dtype=float32, numpy=12.0>

`-` 예제4: with문과 함께 쓰는 tf.GradientTape()_간략한 구문으로 매크로화

In [172]:
x=tf.Variable(2.0)  #미분하고 싶은 애를 Variable로 잡고, 기울기를 구하고 싶은 지점을 숫자로 써라->외우기
a=x/2*3

In [173]:
with tf.GradientTape() as mytape :
    ## with문 시작
    y=a*x**2  # 생략할 수 없는 부분만
    ## with문 끝

In [174]:
mytape.gradient(y,x)  #y를 x로 미분하라.

<tf.Tensor: shape=(), dtype=float32, numpy=12.0>

✏️ **(문법 해설)**    

아래와 같이 쓴다.
```python
with expression(표현식) as myname(이름표를 달아줌) :
    ## with문 시작 : myname.__enter__()
    내가 실행하고 싶은 것을 작성해준다
    ## with문 끝 : myname.__exit__()
```

(1) expression 이 가장 먼저 실행된다. 이 결과로 오브젝트가 생성됨. 생성된 오브젝트는 myname이라고 이름 붙인다. 이 오브젝트는 `.__enter__()`와 `.__exit__()`를 숨겨진 기능으로 포함해야 한다.

(2) with문에 시작되면서 동시에 `myname.__enter__()`이 실행된다.

(3) 내가 실행하고 싶은 것들이 실행된다.

(4) with문에 종료되면서,`myname.__exit__()`이 실행된다.

`-` 예제5: 예제2를 with문과 함께 구현 

In [180]:
x=tf.Variable(2.0)

with tf.GradientTape() as mytape :
    a=x/2*3
    y=a*x**2

mytape.gradient(y,x)  #y를 x로 미분하라.

<tf.Tensor: shape=(), dtype=float32, numpy=18.0>

`-` 예제6: persistent = True

**관찰 1**

In [182]:
# tf.GradientTape? 의 첫줄에 있다.

In [184]:
x=tf.Variable(2.0)

with tf.GradientTape() as mytape :
    a=x/2*3
    y=a*x**2

In [187]:
mytape.gradient(y,x)  #2번째 실행하면 안된다.

RuntimeError: A non-persistent GradientTape can only be used to compute one set of gradients (or jacobians)

- 컴퓨터는 한 번 쓴 연습장을 버림... 그래서 2번째는 실행이 안된다. 일단 버리지 말라고 하는 게 `persistent=True`

**관찰 2**

In [188]:
x=tf.Variable(2.0)

with tf.GradientTape(persistent=True) as mytape :
    a=x/2*3
    y=a*x**2

In [192]:
mytape.gradient(y,x)  # 몇 번 실행해도 오류 없이 잘 된다~!

<tf.Tensor: shape=(), dtype=float32, numpy=18.0>

`-` 예제7: watch

**관찰 1**

In [194]:
x=tf.Variable(2.0)

with tf.GradientTape(persistent=True) as mytape :
    a=x/2*3
    y=a*x**2

mytape.gradient(y,x)

<tf.Tensor: shape=(), dtype=float32, numpy=18.0>

- Variable을 constant로 바꿔보자

In [195]:
x=tf.constant(2.0)

with tf.GradientTape(persistent=True) as mytape :
    a=x/2*3
    y=a*x**2

In [198]:
print(mytape.gradient(y,x))  #결과가 안 나온다.

None


**관찰 2**

In [199]:
x=tf.constant(2.0)

with tf.GradientTape(persistent=True) as mytape :
    mytape.watch(x)
    a=x/2*3
    y=a*x**2

In [200]:
mytape.gradient(y,x)

<tf.Tensor: shape=(), dtype=float32, numpy=18.0>

- `constant`하고 `watch`를 해주면 `Variable`과 같은 결과가 나온다.
- `Variable`로 표현된 오브젝트는 자동 감시(자동으로 watch 메소드 실행)한다.
- `constant`는 수동 감시 한다.

- 어떤 연습장에서는 변수로, 어떤 연습장에서는 상수로 보고 싶을 때가 있다.
- 이게 수동 감시가 필요한 이유!

**관찰 3**
- ??? 자동 감시 모드를 꺼도 되지 않나?

In [205]:
x=tf.Variable(2.0)

with tf.GradientTape(persistent=True, watch_accessed_variables=False) as mytape :
    a=x/2*3
    y=a*x**2

In [206]:
mytape.gradient(y,x)

**관찰 4**
- 관찰해 -> 관찰하지마 -> 관찰해

In [207]:
x=tf.Variable(2.0)

with tf.GradientTape(persistent=True, watch_accessed_variables=False) as mytape :
    mytape.watch(x)
    a=x/2*3
    y=a*x**2

In [208]:
mytape.gradient(y,x)

<tf.Tensor: shape=(), dtype=float32, numpy=18.0>

**관찰 5**
- 관찰해 -> 관찰해 -> 관찰해

In [209]:
x=tf.Variable(2.0)

with tf.GradientTape(persistent=True) as mytape :
    mytape.watch(x)
    a=x/2*3
    y=a*x**2

In [210]:
mytape.gradient(y,x)

<tf.Tensor: shape=(), dtype=float32, numpy=18.0>